name: Build and Push Docker Image

on:
  push:
    branches: [ "master", "main" ]
    paths:
      - 'transcription-service/**'  # Only trigger if changes happen in this folder

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./transcription-service

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ./transcription-service
        file: ./transcription-service/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/transcription-worker:latest
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/transcription-worker:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/transcription-worker:buildcache,mode=max
